version: "3"
services:

    mysql:
      image: mariadb:10.5
      container_name: dlhf-mysql
      working_dir: /app
      volumes:
        - .:/app
        - ./config/mysql/my.cnf:/etc/mysql/conf.d/my.cnf:ro
        - ./.docker/mysqldata:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=default
      ports:
        - "3306:3306"

    webserver:
      image: nginx:1.17-alpine
      container_name: dlhf-webserver
      working_dir: /app
      volumes:
          - .:/app
          - ./config/nginx/:/etc/nginx/conf.d/
          - ./var/log/nginx/:/var/log/nginx/
      ports:
      - "80:80"
    php-fpm:
      build: config/php-fpm
      container_name: dlhf-php-fpm
      working_dir: /app
      volumes:
        - .:/app
        - ./var/log/xdebug/:/var/log/xdebug/
        - ./config/php-fpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/docker-php-overrides.ini
        - ./config/php-fpm/xdebug-ini-overrides.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

